# 参考sample目录下子文件夹的Makefile文件，添加中间的以来文件.o ,obj-y表示添加进去内核
obj-y += user_util.o
obj-y += cmd_downstream_handler.o
obj-y += event_upstream_handler.o


CURRENT_PATH := $(shell pwd)

#包含该路径下的头文件
EXTRA_CFLAGS += \
	-I$(CURRENT_PATH)	\





















